name: roboshop
services:
  mongodb:
    build: ./mongodb
    image: saikrishna580/mongodb:4.0.0 # docker build -t joindevops/mongodb:4.0.0
    container_name: mongodb # docker run -d --network roboshop joindevops/mongodb:4.0.0
  catalogue:
    build: ./catalogue
    image: saikrishna580/catalogue:4.0.0
    container_name: catalogue
    depends_on:
    - mongodb
  frontend:
    build: ./frontend
    image: saikrishna580/frontend:4.0.0
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
    
networks:
  default: # this means all the services in this file use this network
    name: roboshop
    driver: bridge
    external: false # if true it should be created manually, if false docker creates this network